@startmindmap
title id 내부 주요 인력 (1995)\n카맥은 로메로가 프로그래머로서의 감각을 완전히 상실했다고 생각했고\n로메로는 카맥이 더이상 게이머가 아니라고 생각했다\n카맥은 작은 회사에 머무르기를 바란 반면에, 로메로는 회사를 크게 성장시키기를 바랐다.\n한 때 이드를 만들었던 두개의 비전이 이제 회사를 돌이킬 수 없이 분리시키고 있었다.

<style>
mindmapDiagram {
    .silver {
        BackgroundColor silver
    }
    .green {
        BackgroundColor lightgreen
    }
    .orange {
        BackgroundColor #FFA500
    }
    .rose {
        BackgroundColor #FFBBCC
    }
    .blue {
        BackgroundColor lightblue
    }
    .white {
        BackgroundColor #FFFFFF
    }
}
node {
    MaximumWidth 600
}
rootNode {
    MaximumWidth 130
}
</style>

* id 事 (1991.2.1 설립) <<green>>
** 존 카멕 <<orange>>
** 존 로메로 <<orange>>
***_ 팀원들의 질책과 공격, 카멕으로부터의 불만을 듣고 마음이 떠남
*** 톰 홀 (로메로 동업자 과거 @id)
**** 어포지 事 <<green>>
***** 듀크뉴겜3D <<blue>>
******_ 퀘이크 킬러 ㅎㅎ
***_ 톰 홀에게 연락하여 새 회사 차리자고 합의
*** <퀘이크>출시후, 카멕으로부터 사직 강요당함<<rose>>
** 에이드리안
** 케빈
** 아메리칸
***_ <스트라이프>게임 작업을 위해 팀을 고용함
*** 팀 월리츠
****_ (입사) 둠 게임 레벨 편집툴로 레벨 수정본 공유한 것이 인지도를 얻어 id로부터 입사제안 받음
****_ 카멕에게 작품을 인정받음, 로메로와 경쟁, 새로운 패권 장악 욕심
**** <퀘이크> 쉐어웨어 오프닝 레벨 담당으로 지정됨 (by 카멕) <-> 로메로의 반발<<rose>>
***_ 이제 아메리칸만 동떨어진 상황을 맞이함-><퀘이크>음악 담당, 카맥과 점점 단절
** 퀘이크 <<blue>>
***_ 이질적인 작업물 통일성 부재
****_ 16개월동안 개발한 각 담당자의 산출물이 통합되지 않음\n로메로의 레벨은 중세, 아메리칸의 레벨은 미래지향적, 샌디의 레벨은 고딕 퍼즐
***_ 1996.6.22 게임 완성

@endmindmap